    - name: import app setup from common role
      ansible.builtin.import_role:
        name: common
        tasks_from: app-setup.yml
    
    - name: import common role
      ansible.builtin.import_role:
        name: common
        tasks_from: nodejs.yml

    - name: import systemd setup from common role
      ansible.builtin.import_role:
        name: common
        tasks_from: systemd-setup.yml
