  - name: setup {{ component }} service 
    ansible.builtin.template:
      src: "{{ component }}.service.j2" #ansible opens templates and replaces
      dest: /etc/systemd/system/{{ component }}.service
    notify: daemon reload  


  - name: enable and start {{ component }}
    ansible.builtin.service:
      name: "{{ component }}"
      state: restarted
      enabled: yes
